# Configuration for Extras plugin
allowJoinOnFullServer: false
enableKick: false
enableJoinRestrictions: false
opOnJoin: true
playerJoinTitle: "§7Welcome to Kapow!"
playerJoinSubtitle: "Free OP • Anarchy • Creative"
opTag: "§4§l[§c§lOP§4§l] §r§c"
deOpTag: "§8§l[§7§lDeOP§8§l] §r§7"